FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_NO_CACHE_DIR=on

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src ./src

EXPOSE 8080

CMD ["sh", "-c", "uvicorn src.fastapi_app.main:app --host 0.0.0.0 --port $PORT"]

